const checkRetries = require('./lib/steps/check-retries')
const getNextJobFromQueue = require('./lib/steps/get-next-job-from-queue')
const getFileData = require('./lib/steps/get-file-data')
const prepareData = require('./lib/steps/prepare-data')
const sendToSigning = require('./lib/steps/send-to-signing')
const saveToCallback = require('./lib/steps/save-to-callback')
const generateDummy = require('./lib/steps/generate-dummy')
const saveToDone = require('./lib/steps/save-to-done')
const saveToRetries = require('./lib/steps/save-to-retries')
const saveToErrors = require('./lib/steps/save-to-errors')
const removeFromQueue = require('./lib/steps/remove-from-queue')
const logger = require('./lib/logger')

logger('info', ['index', 'start'])

checkRetries()
  .then(getNextJobFromQueue)
  .then(getFileData)
  .then(prepareData)
  .then(sendToSigning)
  .then(saveToCallback)
  .then(generateDummy)
  .then(saveToDone)
  .then(saveToErrors)
  .then(saveToRetries)
  .then(removeFromQueue)
  .then(data => {
    logger('info', ['index', data._id, 'finished'])
    process.exit(0)
  })
  .catch(error => {
    logger('error', ['index', 'error', JSON.stringify(error)])
    process.exit(1)
  })
